FROM registry.gitlab.com/thonglorpet-hrms/hrms-api:stage1
WORKDIR /var/www
ARG BUILD_VER_ARG=test1.0.0
ENV BUILD_VER="${BUILD_VER_ARG}"
# COPY hrms-api/ .
COPY . .
RUN composer update
RUN composer install
EXPOSE 8080
CMD ["php","artisan","serve","--host=0.0.0.0","--port=8080"]

